services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    secrets:
      - app_secret_key
      - postgres_password
    environment:
      # Your app must support reading these files.
      APP_SECRET_KEY_FILE: /run/secrets/app_secret_key
      DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
      ADMIN_PASSWORD: /run/secrets/adminpassword.txt
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: main
      DATABASE_USER: postgres

  db:
    image: docker.io/library/postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  app_secret_key:
    file: ./secrets/app_secret_key.txt