ktor:
  deployment:
    port: 8080
  application:
    modules:
      - cantstopthesignal.config.HttpKt.configureHttp
      - cantstopthesignal.config.SerializationKt.configureSerialization
      - cantstopthesignal.security.SecurityKt.configureSecurity
      - cantstopthesignal.security.RateLimitingKt.configureRateLimiting
      - com.freedom.ThymeleafKt.configureThymeleaf
      - cantstopthesignal.config.StatusPagesKt.configureStatusPages
      - cantstopthesignal.config.RoutingKt.configureRouting
      - cantstopthesignal.routing.IndexKt.indexRouting

