ktor:
  deployment:
    host: "0.0.0.0"
    port: 8080
  application:
    modules:
      - cantstopthesignal.config.HttpKt.configureHttp
      - cantstopthesignal.config.CustomizationKt.loadSiteConfig
      - cantstopthesignal.config.MonitoringKt.configureMonitoring
      - cantstopthesignal.security.SecurityKt.configureSecurity
      - cantstopthesignal.config.RateLimitingKt.configureRateLimiting
      - cantstopthesignal.config.ThymeleafKt.configureThymeleaf
      - cantstopthesignal.config.StatusPagesKt.configureStatusPages
      - cantstopthesignal.routing.login.IndexRoutingKt.indexRouting
      - cantstopthesignal.routing.login.LoginRoutingKt.configureLoginRoutes
      - cantstopthesignal.routing.login.SignUpRoutingKt.configureSignupRoutes
      - cantstopthesignal.routing.posts.PostsRoutingKt.configurePostRouting
      - cantstopthesignal.config.DatabaseKt.configureDatabase
      - cantstopthesignal.routing.profile.MyProfileRoutingKt.configureProfileRoutes
      - cantstopthesignal.routing.profile.NotificationsRoutingKt.configureNotificationRoutes
      - cantstopthesignal.routing.posts.PostCreationRoutingKt.configurePostCreationRouting
      - cantstopthesignal.routing.messages.PrivateMessagesRoutingKt.configureMessageRouting
      - cantstopthesignal.routing.comments.CommentsRoutingKt.configureCommentsRouting
      - cantstopthesignal.routing.comments.CommentRepliesRoutingKt.configureCommentRepliesRouting
      - cantstopthesignal.routing.posts.PostLikesRoutingKt.configurePostLikesRouting
      - cantstopthesignal.routing.comments.CommentLikesRoutingKt.configureCommentLikesRouting
      - cantstopthesignal.routing.profile.ProfileEditingRoutingKt.configureEditProfileRoutes
      - cantstopthesignal.routing.admin.AdminPanelRoutingKt.configureAdminRoutes
      - cantstopthesignal.routing.posts.PostSearchRoutingKt.configurePostSearchRouting
      - cantstopthesignal.routing.posts.PostEditRoutingKt.configurePostEditingRouting




site:
  name: "Can't Stop The Signal." # Your service name, displayed as part of the header card
  topic: "Anonymous discussion, uncensored." #A little blurb about your service, could be cooking related if its a cooking forum, gardening related if its gardening , etc.
  motd: "“There is some good in this world, and it’s worth fighting for.” — Samwise Gamgee" # This is configurable from the admin panel, but this is the default value upon starting the server and will wipe whatever transient value was set by admins
  pgp_help: "You should share PGP keys with members. You should always encrypt private messages."
  pgp_warning: "Your PGP key will have a name email attached, if this is for totally anonymous use, you should make sure the key you share has a pseudonym and a fake or anonymous email handle."
  audience: "cantstopthesignal"
  issuer: "cantstopthesignal.i2p" #This and the one after is just for your token, it doesnt necessarily matter that much but you should set it your i2p service name for consistency
  baseUrl: "http://cantstopthesignal.i2p"
  token_lifetime_minutes: "25" #There is no token invalidation done so it is recommended to keep this value below 30 minutes , you can put it higher just bare in mind session hijacking risk grows with this value
  invite_only: "false" # I will use this to make it so that users require a special invite code or similar to sign up so people can host private forums. This can be changed in the admin panel. If this option here is true, it cannot be overridden from the admin panel. If it is false, then admins can turn it on or off as they wish.
  rate_limit_window_seconds: "20" #This and the below rate limit va
  rate_limit_num_allowed_in_window: "350"
  rate_limit_window_seconds_login_signup: "5"
  rate_limit_num_allowed_in_window_login_signup: "10"
  message_deletion_window_hours: "48" #When a private message convo has deleting messages on, how many hours between clears? It ONLY clears if all messages have been read in th conversation by all members, so be wary
  signups_disabled: "false" # This can be done from the admin panel, but we will make a superceding config option for it. If it is enabled here it cannot be overridden by admins
  pgp_login_only: "false" # If this is enabled, there are no passwords and users must sign via PGP signature challenge. This option should not be changed later, it should be decided when you first decide to host an instance of this service. Note: I have since updated this to allow passwordless users in a non forced pgp login context, so it is safe(r) to change this once you have a userbase.
