ktor:
  deployment:
    host: "0.0.0.0"
    port: 8080
  application:
    modules:
      - cantstopthesignal.config.HttpKt.configureHttp
      - cantstopthesignal.config.CustomizationKt.loadSiteConfig
      - cantstopthesignal.config.SerializationKt.configureSerialization
      - cantstopthesignal.security.SecurityKt.configureSecurity
      - cantstopthesignal.config.RateLimitingKt.configureRateLimiting
      - com.freedom.ThymeleafKt.configureThymeleaf
      - cantstopthesignal.config.StatusPagesKt.configureStatusPages
      - cantstopthesignal.config.RoutingKt.configureRouting
      - cantstopthesignal.routing.login.IndexRoutingKt.indexRouting
      - com.freedom.cantstopthesignal.routing.LoginRoutingKt.configureLoginRoutes
      - cantstopthesignal.routing.login.SignUpRoutingKt.configureSignupRoutes
      - cantstopthesignal.routing.posts.PostsRoutingKt.configurePostRouting
      - cantstopthesignal.config.DatabaseKt.configureDatabase
      - cantstopthesignal.routing.profile.MyProfileRoutingKt.configureProfileRoutes
      - cantstopthesignal.routing.profile.NotificationsRoutingKt.configureNotificationRoutes
      - cantstopthesignal.routing.posts.PostCreationRoutingKt.configurePostCreationRouting
      - cantstopthesignal.routing.messages.PrivateMessagesRoutingKt.configureMessageRouting
      - com.freedom.cantstopthesignal.routing.comments.CommentsRoutingKt.configureCommentsRouting
      - com.freedom.cantstopthesignal.routing.comments.CommentRepliesRoutingKt.configureCommentRepliesRouting
      - com.freedom.cantstopthesignal.routing.posts.PostLikesRoutingKt.configurePostLikesRouting
      - com.freedom.cantstopthesignal.routing.comments.CommentLikesRoutingKt.configureCommentLikesRouting
      - cantstopthesignal.routing.profile.ProfileEditingRoutingKt.configureEditProfileRoutes
      - com.freedom.cantstopthesignal.routing.admin.AdminPanelRoutingKt.configureAdminRoutes
      - com.freedom.cantstopthesignal.routing.posts.PostSearchRoutingKt.configurePostSearchRouting




site:
  name: "Can't Stop The Signal."
  topic: "Anonymous discussion, uncensored."
  motd: "“There is some good in this world, and it’s worth fighting for.” — Samwise Gamgee"
  pgp_help: "You should share PGP keys with members. You should always encrypt private messages."
  no_encrypt_warning_group: "Someone in this group does not have a public key uploaded! The chat cannot be encrypted! Do not share personal information until all members have PGP keys uploaded!"
  no_encrypt_warning_individual: "The person you are messaging does not have a public key uploaded! You should be locally encryptingDo not share personal information until all members have PGP keys uploaded!"
  encryption_explanation: "You should upload a PGP key for private messages, but you do not have to. It will make your communication much more private and secure, otherwise the messages with live plaintext on a server. If there is no identifiable information then it is not a huge deal, however it is always best to encrypt."
  pgp_warning: "Your PGP key will have a name email attached, if this is for totally anonymous use, you should make sure the key you share has a pseudonym and a fake or anonymous email handle."
  audience: "cantstopthesignal"
  issuer: "cantstopthesignal.i2p"
  baseUrl: "http://cantstopthesignal.i2p"
  token_lifetime_minutes: "15"
  invite_only: "false" # I will use this to make it so that users require a special invite code or similar to sign up so people can host private forums
  rate_limit_window_seconds: "20"
  rate_limit_num_allowed_in_window: "350"
  rate_limit_window_seconds_login_signup: "5"
  rate_limit_num_allowed_in_window_login_signup: "10"
  signups_disabled: "false" # This can be done from the admin panel, but we will make a superceding config option for it
  pgp_login_only: "false" # If this is enabled, there are no passwords and users must sign via PGP signature challenge
